/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqlitetrabajo;

import java.sql.*;

/**
 *
 * @author David
 */
public class MusicaInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form MusicaInterfaz
     */
    public MusicaInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jComboEstilo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();
        bConsultar = new javax.swing.JButton();
        jComboTipo = new javax.swing.JComboBox<>();
        etEstilo = new javax.swing.JLabel();
        etEstilo1 = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();
        jTextBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jComboEstilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEstiloActionPerformed(evt);
            }
        });

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        bConsultar.setText("consultar");
        bConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarActionPerformed(evt);
            }
        });

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoActionPerformed(evt);
            }
        });

        etEstilo.setText("Ordenar por estilo:");

        etEstilo1.setText("Ordenar por tipo:");

        bVolver.setText("volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        jLabel1.setText("Buscar por nombre:");

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(bConsultar)
                        .addGap(64, 64, 64)
                        .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etEstilo))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etEstilo1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etEstilo)
                    .addComponent(etEstilo1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bConsultar)
                    .addComponent(bVolver))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboEstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEstiloActionPerformed
        
    }//GEN-LAST:event_jComboEstiloActionPerformed

    private void bConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarActionPerformed
        ejecutaConsulta();
        buscar();
        jTextBuscar.setText("");
    }//GEN-LAST:event_bConsultarActionPerformed

    private void jComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        InterfazPrincipal principal = new InterfazPrincipal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_bVolverActionPerformed
    
    private Connection miConexion;
    private PreparedStatement enviaConsultaEstilos;
    private String consultaEstilos="select id,nombre,artista,estilo,cdvinilo,precio from TablaMusica where estilo=?";
    private PreparedStatement enviaConsultaTipos;
    private String consultaTipos="select id,nombre,artista,estilo,cdvinilo,precio from TablaMusica where cdvinilo=?";
    private PreparedStatement enviaConsultaTodos;
    private String consultaTodos="select id,nombre,artista,estilo,cdvinilo,precio from TablaMusica where estilo=? and cdvinilo=?";
    
    //Creo la conexión con la Base de Datos.
    //Creo dos variables en las que recojo el estilo musica y el tipo de formato.
    //Y los resultados de esas variables los recoge el ResultSet y las añado a sus jComboBox adecuados.
    public void jComboEstilos(){
        try{
            miConexion=DriverManager.getConnection("jdbc:sqlite:tablavinilos.db");
            Statement miStatement=miConexion.createStatement();
            String consultaEstilos="select distinct estilo from TablaMusica";
            String consultaTipos="select distinct cdvinilo from TablaMusica";
            ResultSet miResultSetEstilos=miStatement.executeQuery(consultaEstilos);
            while(miResultSetEstilos.next()){
                jComboEstilo.addItem(miResultSetEstilos.getString(1));
            }
            ResultSet miResultSetTipos=miStatement.executeQuery(consultaTipos);
            while(miResultSetEstilos.next()){
                jComboTipo.addItem(miResultSetTipos.getString(1));
            }
            
        }catch(Exception e){
            System.out.println("ERROR "+e);
        }
    }

    public void ejecutaConsulta(){
        ResultSet miResultSet=null;
        
        try{
            jTextArea.setText(""); //<-Al ejecutar otra consultaEstilos con otro estilo, se ponga el jTextArea en blanco.
            String estilo=(String)jComboEstilo.getSelectedItem(); //Guarda lo que seleccionó el usuario.
            String tipo=(String)jComboTipo.getSelectedItem(); //Guarda lo que seleccionó el usuario.
            
            //Si ha seleccionado algo diferente a "Seleccionar" && si ha seleccionado "Seleccionar".
            //Si ha seleccionado algo diferente a "Seleccionar" se muestra el estilo musical que ha seleccionado el usuario.
            if(!estilo.equals("Seleccionar") && tipo.equals("Seleccionar")){ 
                enviaConsultaEstilos=miConexion.prepareStatement(consultaEstilos);
                enviaConsultaEstilos.setString(1, estilo);
                miResultSet=enviaConsultaEstilos.executeQuery();
            //Si si ha seleccionado "Seleccionar" && ha seleccionado algo diferente a "Seleccionar".
            //Si ha seleccionado algo diferente a "Seleccionar" se muestra el tipo de formato que ha seleccionado el usuario.
            }else if(estilo.equals("Seleccionar") && !tipo.equals("Seleccionar")){
                enviaConsultaTipos=miConexion.prepareStatement(consultaTipos);
                enviaConsultaTipos.setString(1, tipo);
                miResultSet=enviaConsultaTipos.executeQuery();
            //Si los dos los dos seleccionan algo diferente a "Seleccionar" se muestra el estilo y el tipo de formato seleccionado.
            }else if(!estilo.equals("Seleccionar") && !tipo.equals("Seleccionar")){
                enviaConsultaTodos=miConexion.prepareStatement(consultaTodos);
                enviaConsultaTodos.setString(1, estilo);
                enviaConsultaTodos.setString(2, tipo);
                miResultSet=enviaConsultaTodos.executeQuery();
            }

            //Dento de un while muestro en un JTextArea lo que recoge el ResultSet llamado "miResultSet"
            while(miResultSet.next()){
                jTextArea.append(miResultSet.getString(1));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(2));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(3));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(4));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(5));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(6));
                jTextArea.append("\n");
            }
            
        }catch(Exception e){
            
        }
    }
    
    //Inserto el nombre del disco que quiero buscar en un JTextField.
    //Se ejecuta la consulta de sql.
    //Y se añade al JTextArea.
    public void buscar(){
        ResultSet miResultSet=null;
        PreparedStatement enviaConsultaBusqueda;
        String consultaBusqueda="select * from TablaMusica where nombre='"+jTextBuscar.getText()+"'";
        try{
            enviaConsultaBusqueda=miConexion.prepareStatement(consultaBusqueda);
            miResultSet=enviaConsultaBusqueda.executeQuery();
            
            while(miResultSet.next()){
                jTextArea.append(miResultSet.getString(1));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(2));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(3));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(4));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(5));
                jTextArea.append(", ");
                jTextArea.append(miResultSet.getString(6));
                jTextArea.append("\n");
            }
        }catch(Exception e){
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicaInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConsultar;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel etEstilo;
    private javax.swing.JLabel etEstilo1;
    private javax.swing.JComboBox<String> jComboEstilo;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    private javax.swing.JTextField jTextBuscar;
    // End of variables declaration//GEN-END:variables
}
