/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sqlitetrabajo;

import java.awt.Point;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.*;
import javax.swing.JTable;

/**
 *
 * @author David
 */
public class OperacionesBDInterfaz extends javax.swing.JFrame {
    
    DefaultTableModel modeloTabla=new DefaultTableModel(null,getColumnas());
    ConexionSQL obxC=new ConexionSQL();
    ConexionSQL obxConexion=new ConexionSQL();

    /**
     * Creates new form OperacionesBDInterfaz
     */
    
    public OperacionesBDInterfaz() throws SQLException {
        modeloTabla=new DefaultTableModel(null,getColumnas());
        mostrarTabla();
        initComponents();
    }
    
    //Este método, recoge un Array con los campos de la tabla de la base de datos.
    private String[] getColumnas(){
        String columna[]=new String[]{"ID","NOMBRE","ARTISTA","ESTILO","CD/VINILO","PRECIO"};
        return columna;
    }
    
    //En la variable llamada "sql" recojo una sentencia sql, con todos los campos de la tabla "TablaMusica" de la Base de Datos.
    //Creo un Array de tipo Object, con 6 posiciones como campos tiene la tabla.
    //Con el while -> Mientras en el ResultSet haya algún registro se añade al Array.
    //Y finalmente se añade a la tabla (JTable).
    public void mostrarTabla(){
        borrarTabla(); //Meto el método "borrarTabla" para que se ejecute el método
        try{
            String sql="select id,nombre,artista,estilo,cdvinilo,precio from TablaMusica";
            PreparedStatement miStatement=obxC.entrar().prepareStatement(sql);
            ResultSet miResultSet=miStatement.executeQuery();
            Object datos[]=new Object[6];
            
            while(miResultSet.next()){
                for(int i=0;i<6;i++){
                    datos[i]=miResultSet.getObject(i+1);
                }
                modeloTabla.addRow(datos);
            }
            miResultSet.close();
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    //Recorro la tabla dependiendo con el número filas que tenga.
    //Y elimino la fila
    public void borrarTabla(){
        for(int i=0;i<modeloTabla.getRowCount();i++){
            modeloTabla.removeRow(i);
            i-=1;
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        etDiscografia = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        jTextId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextIdActualizar = new javax.swing.JTextField();
        etId = new javax.swing.JLabel();
        jTextCampo = new javax.swing.JTextField();
        etMod = new javax.swing.JLabel();
        jTextNuevoDato = new javax.swing.JTextField();
        etNewDato = new javax.swing.JLabel();
        etActualizar = new javax.swing.JLabel();
        bActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        etDiscografia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        etDiscografia.setText("TODA LA DISCOGRAFIA DISPONIBLE:");

        bVolver.setText("Volver");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Escribir el ID que quiero borrar:");

        etId.setText("ID del producto:");

        jTextCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCampoActionPerformed(evt);
            }
        });

        etMod.setText("Campo a modificar:");

        etNewDato.setText("Nuevo dato:");

        etActualizar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        etActualizar.setText("Actualizar datos:");

        bActualizar.setText("Actualizar");
        bActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextIdActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etId))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etMod))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etNewDato)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addComponent(jTextNuevoDato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bActualizar))))
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(276, 276, 276))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(etActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(etDiscografia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(etDiscografia)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrar)
                    .addComponent(jTextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etActualizar)
                    .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etId)
                    .addComponent(etMod)
                    .addComponent(etNewDato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIdActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNuevoDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bActualizar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        InterfazPrincipal principal = new InterfazPrincipal();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_bVolverActionPerformed
    
    //Con el objeto "obxC" de la clase ConexionSQL, llamo al método "entrar", este método se conecta con la Base de Datos.
    //Se ejecuta la sentencia sql.
    //Y muestra toda la tabla sin el campo borrado.
    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        try {
            PreparedStatement st=obxC.entrar().prepareStatement("delete from TablaMusica where id='"+jTextId.getText()+"'");
            st.executeUpdate();
            mostrarTabla();
            jTextId.setText("");
        } catch (SQLException ex) {
            System.out.println("NO eliminó el producto. * ERROR *");
        }
        obxC.close();
    }//GEN-LAST:event_bBorrarActionPerformed

    private void jTextCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCampoActionPerformed
        
    }//GEN-LAST:event_jTextCampoActionPerformed

    //Con el objeto "obxC" de la clase ConexionSQL, llamo al método "entrar", este método se conecta con la Base de Datos.
    //Se ejecuta la sentencia sql, recogemos los campos introducidos en los JTextField.
    //Y muestra la tabla con los campos actualizados.
    private void bActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarActionPerformed
        try {
            PreparedStatement st=obxC.entrar().prepareStatement("update TablaMusica set "+jTextCampo.getText()+"='"+jTextNuevoDato.getText()+"' where id='"+jTextIdActualizar.getText()+"'");
            st.executeUpdate();
            mostrarTabla();
            jTextIdActualizar.setText("");
            jTextCampo.setText("");
            jTextNuevoDato.setText("");
        } catch (SQLException ex) {
            System.out.println("NO eliminó el producto. * ERROR *");
        }
        obxC.close();
    }//GEN-LAST:event_bActualizarActionPerformed

    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OperacionesBDInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OperacionesBDInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OperacionesBDInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OperacionesBDInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OperacionesBDInterfaz().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(OperacionesBDInterfaz.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizar;
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel etActualizar;
    private javax.swing.JLabel etDiscografia;
    private javax.swing.JLabel etId;
    private javax.swing.JLabel etMod;
    private javax.swing.JLabel etNewDato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextCampo;
    private javax.swing.JTextField jTextId;
    private javax.swing.JTextField jTextIdActualizar;
    private javax.swing.JTextField jTextNuevoDato;
    // End of variables declaration//GEN-END:variables
}
